// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Ruptura.Infrastructure.Data;

#nullable disable

namespace Ruptura.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260805000815_SeedOriginsAndBackgrounds")]
    partial class SeedOriginsAndBackgrounds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Ruptura.Domain.Entities.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameMasterId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("Ruptura.Domain.Entities.CampaignMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId", "PlayerId")
                        .IsUnique();

                    b.ToTable("CampaignMemberships");
                });

            modelBuilder.Entity("Ruptura.Domain.Entities.CatalogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByGameMasterId")
                        .HasColumnType("uuid");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Type", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_catalog_entries_global_type_name")
                        .HasFilter("\"CampaignId\" IS NULL");

                    b.HasIndex("Type", "CampaignId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_catalog_entries_scoped_type_campaign_name")
                        .HasFilter("\"CampaignId\" IS NOT NULL");

                    b.ToTable("CatalogEntries");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataJson = "{\"MainBenefit\":\"-1 dificuldade em testes de Disciplina/forma\\u00E7\\u00E3o em combate organizado\",\"PrimarySkill\":\"Espadas\",\"SecondarySkill\":\"Armaduras\",\"StartingEquipment\":\"Espada curta, armadura leve\",\"NarrativeHook\":\"Desertou ou foi dispensado de uma for\\u00E7a militar local\"}",
                            Name = "Soldado",
                            Type = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataJson = "{\"MainBenefit\":\"-1 dificuldade em Rastreamento na natureza\",\"PrimarySkill\":\"Rastreamento\",\"SecondarySkill\":\"Arcos\",\"StartingEquipment\":\"Arco simples, capa\",\"NarrativeHook\":\"Vive das terras selvagens h\\u00E1 anos\"}",
                            Name = "Caçador",
                            Type = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataJson = "{\"MainBenefit\":\"Pode identificar qualidade de materiais sem teste\",\"PrimarySkill\":\"Ferraria\",\"SecondarySkill\":\"Avalia\\u00E7\\u00E3o\",\"StartingEquipment\":\"Ferramentas de artes\\u00E3o\",\"NarrativeHook\":\"Aprendeu um of\\u00EDcio com um mestre exigente\"}",
                            Name = "Artesão",
                            Type = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataJson = "{\"MainBenefit\":\"\\u002B1 recupera\\u00E7\\u00E3o extra em descanso longo\",\"PrimarySkill\":\"Sobreviv\\u00EAncia\",\"SecondarySkill\":\"Conhecimento de Animais\",\"StartingEquipment\":\"Foice, roupas simples\",\"NarrativeHook\":\"Cresceu trabalhando a terra\"}",
                            Name = "Camponês",
                            Type = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataJson = "{\"MainBenefit\":\"1x por interl\\u00FAdio, resolve uma d\\u00FAvida factual sem gastar tempo de pesquisa\",\"PrimarySkill\":\"Hist\\u00F3ria (ou Teoria Arcana)\",\"SecondarySkill\":\"Linguagens\",\"StartingEquipment\":\"Livro pessoal\",\"NarrativeHook\":\"Passou a juventude entre pergaminhos\"}",
                            Name = "Estudioso",
                            Type = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataJson = "{\"MainBenefit\":\"Pre\\u00E7os com o comerciante viajante 10% melhores\",\"PrimarySkill\":\"Com\\u00E9rcio\",\"SecondarySkill\":\"Avalia\\u00E7\\u00E3o\",\"StartingEquipment\":\"Bolsa de moedas extra\",\"NarrativeHook\":\"Cresceu entre balc\\u00F5es e negocia\\u00E7\\u00F5es\"}",
                            Name = "Comerciante",
                            Type = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataJson = "{\"MainBenefit\":\"Possui 1 contato de influ\\u00EAncia acion\\u00E1vel (uso limitado)\",\"PrimarySkill\":\"Lideran\\u00E7a\",\"SecondarySkill\":\"Diplomacia\",\"StartingEquipment\":\"Anel de fam\\u00EDlia (sem valor comercial)\",\"NarrativeHook\":\"Perdeu t\\u00EDtulo ou heran\\u00E7a\"}",
                            Name = "Nobre Decaído",
                            Type = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000008"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataJson = "{\"MainBenefit\":\"-1 dificuldade em Furtividade em ambiente urbano\",\"PrimarySkill\":\"Furtividade\",\"SecondarySkill\":\"Manipula\\u00E7\\u00E3o\",\"StartingEquipment\":\"Ferramentas de arrombamento\",\"NarrativeHook\":\"Tem um passado que a Guilda desconhece\"}",
                            Name = "Criminoso",
                            Type = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000009"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataJson = "{\"MainBenefit\":\"1x por expedi\\u00E7\\u00E3o, realiza uma pequena b\\u00EAn\\u00E7\\u00E3o ritual (efeito menor)\",\"PrimarySkill\":\"Religi\\u00E3o\",\"SecondarySkill\":\"Rituais\",\"StartingEquipment\":\"S\\u00EDmbolo sagrado\",\"NarrativeHook\":\"Serviu um templo antes de ingressar na Guilda\"}",
                            Name = "Sacerdote",
                            Type = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000010"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataJson = "{\"MainBenefit\":\"-1 dificuldade em Equil\\u00EDbrio/terreno inst\\u00E1vel\",\"PrimarySkill\":\"Nata\\u00E7\\u00E3o\",\"SecondarySkill\":\"Armas de Arremesso\",\"StartingEquipment\":\"Corda, faca\",\"NarrativeHook\":\"Passou anos em embarca\\u00E7\\u00F5es\"}",
                            Name = "Marinheiro",
                            Type = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000011"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataJson = "{\"MainBenefit\":\"Nunca fica \\u0022perdido\\u0022 narrativamente (sempre sabe a dire\\u00E7\\u00E3o geral)\",\"PrimarySkill\":\"Navega\\u00E7\\u00E3o\",\"SecondarySkill\":\"Sobreviv\\u00EAncia\",\"StartingEquipment\":\"Cantil resistente\",\"NarrativeHook\":\"Nunca teve um lar fixo\"}",
                            Name = "Nômade",
                            Type = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000012"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataJson = "{\"MainBenefit\":\"-1 dificuldade em identificar instabilidades em cavernas e t\\u00FAneis\",\"PrimarySkill\":\"Constru\\u00E7\\u00E3o\",\"SecondarySkill\":\"Percep\\u00E7\\u00E3o\",\"StartingEquipment\":\"Picareta\",\"NarrativeHook\":\"Trabalhou em minas antes de se tornar aventureiro\"}",
                            Name = "Mineiro",
                            Type = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000013"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataJson = "{\"MainBenefit\":\"1x por expedi\\u00E7\\u00E3o, estabiliza um ferido grave sem instala\\u00E7\\u00E3o\",\"PrimarySkill\":\"Medicina\",\"SecondarySkill\":\"Po\\u00E7\\u00F5es\",\"StartingEquipment\":\"Kit m\\u00E9dico b\\u00E1sico\",\"NarrativeHook\":\"Cuidou de doentes numa vila ou tropa\"}",
                            Name = "Curandeiro",
                            Type = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000014"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataJson = "{\"MainBenefit\":\"-1 dificuldade em testes sociais para obter informa\\u00E7\\u00E3o de estranhos\",\"PrimarySkill\":\"Diplomacia\",\"SecondarySkill\":\"Manipula\\u00E7\\u00E3o\",\"StartingEquipment\":\"Instrumento simples\",\"NarrativeHook\":\"Viajou de vila em vila contando hist\\u00F3rias\"}",
                            Name = "Menestrel",
                            Type = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000015"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataJson = "{\"MainBenefit\":\"-1 dificuldade em Percep\\u00E7\\u00E3o para notar armadilhas/emboscadas em ambientes fechados\",\"PrimarySkill\":\"Percep\\u00E7\\u00E3o\",\"SecondarySkill\":\"Furtividade\",\"StartingEquipment\":\"Faca pequena escondida\",\"NarrativeHook\":\"Sobreviveu sozinho nas ruas\"}",
                            Name = "Órfão de Rua",
                            Type = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000016"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataJson = "{\"MainBenefit\":\"Conhece 1 idioma/s\\u00EDmbolo raro exclusivo do grupo\",\"PrimarySkill\":\"Linguagens\",\"SecondarySkill\":\"Rastreamento\",\"StartingEquipment\":\"Nenhum (perdeu tudo)\",\"NarrativeHook\":\"Foi expulso de sua terra natal por um motivo que s\\u00F3 ele sabe\"}",
                            Name = "Exilado",
                            Type = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000017"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataJson = "{\"MainBenefit\":\"Reconhece automaticamente s\\u00EDmbolos/rituais de cultos, sem teste\",\"PrimarySkill\":\"Rituais\",\"SecondarySkill\":\"Religi\\u00E3o\",\"StartingEquipment\":\"Adaga cerimonial\",\"NarrativeHook\":\"Abandonou um culto antes que fosse tarde demais\"}",
                            Name = "Ex-Cultista",
                            Type = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000018"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataJson = "{\"MainBenefit\":\"Recebe 5 pontos extras de per\\u00EDcia para investir em Dungeonologia\",\"PrimarySkill\":\"Dungeonologia\",\"SecondarySkill\":\"Estrat\\u00E9gia\",\"StartingEquipment\":\"Mapa desatualizado da Guilda\",\"NarrativeHook\":\"Cresceu dentro da pr\\u00F3pria Guilda, filho de um veterano\"}",
                            Name = "Pupilo da Guilda",
                            Type = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000019"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataJson = "{\"MainBenefit\":\"-1 dificuldade em Rastreamento de um alvo espec\\u00EDfico definido\",\"PrimarySkill\":\"Rastreamento\",\"SecondarySkill\":\"Intimida\\u00E7\\u00E3o\",\"StartingEquipment\":\"Grilh\\u00F5es, arco leve\",\"NarrativeHook\":\"Vivia de capturar fugitivos e criaturas fugidas\"}",
                            Name = "Caçador de Recompensas",
                            Type = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000020"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataJson = "{\"MainBenefit\":\"-1 dificuldade no primeiro teste de qualquer nova magia aprendida\",\"PrimarySkill\":\"Controle M\\u00E1gico\",\"SecondarySkill\":\"Teoria Arcana\",\"StartingEquipment\":\"Grim\\u00F3rio incompleto\",\"NarrativeHook\":\"Estudou magia formalmente, mas nunca se formou\"}",
                            Name = "Estudante Arcano",
                            Type = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataJson = "{\"TriggeringEvent\":\"Explorou uma constru\\u00E7\\u00E3o antiga e escapou\",\"Benefit\":\"-1 dificuldade para identificar riscos estruturais/desabamentos\",\"Complication\":\"Algo daquela ru\\u00EDna ainda o procura\"}",
                            Name = "Sobrevivente de Ruína",
                            Type = 1,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataJson = "{\"TriggeringEvent\":\"Seu grupo anterior foi dizimado\",\"Benefit\":\"1x por expedi\\u00E7\\u00E3o, ignora a condi\\u00E7\\u00E3o de Surpreendido\",\"Complication\":\"Sofre rea\\u00E7\\u00F5es intensas a situa\\u00E7\\u00F5es que lembrem a emboscada\"}",
                            Name = "Sobreviveu a uma Emboscada",
                            Type = 1,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataJson = "{\"TriggeringEvent\":\"Passou tempo confinado, injustamente ou n\\u00E3o\",\"Benefit\":\"Vantagem para escapar de conten\\u00E7\\u00F5es f\\u00EDsicas (cordas, algemas)\",\"Complication\":\"Possui um registro criminal reconhec\\u00EDvel por autoridades\"}",
                            Name = "Foi Preso",
                            Type = 1,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataJson = "{\"TriggeringEvent\":\"Sua unidade foi dizimada em combate\",\"Benefit\":\"Resist\\u00EAncia maior ao medo em combate organizado\",\"Complication\":\"Um superior sobrevivente o culpa pela derrota\"}",
                            Name = "Serviu no Exército",
                            Type = 1,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataJson = "{\"TriggeringEvent\":\"Teve um mentor renomado que sumiu\",\"Benefit\":\"Pode invocar o nome do mestre para abrir portas em um c\\u00EDrculo espec\\u00EDfico\",\"Complication\":\"O desaparecimento do mestre esconde algo perigoso\"}",
                            Name = "Estudou com um Mestre",
                            Type = 1,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataJson = "{\"TriggeringEvent\":\"Per\\u00EDodo de mis\\u00E9ria extrema\",\"Benefit\":\"Aguenta mais tempo sem comida antes de sofrer penalidades\",\"Complication\":\"Deve favores a uma rede do submundo\"}",
                            Name = "Viveu nas Ruas",
                            Type = 1,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataJson = "{\"TriggeringEvent\":\"Recebeu um objeto de fam\\u00EDlia com hist\\u00F3ria\",\"Benefit\":\"O item herdado carrega uma pequena propriedade extra\",\"Complication\":\"Algu\\u00E9m mais tamb\\u00E9m quer aquele objeto de volta\"}",
                            Name = "Herdou uma Ferramenta",
                            Type = 1,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000008"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataJson = "{\"TriggeringEvent\":\"Achou um documento que n\\u00E3o deveria ter achado\",\"Benefit\":\"Conhece um fragmento raro de informa\\u00E7\\u00E3o (nome, s\\u00EDmbolo, local)\",\"Complication\":\"Outros sabem que ele tem o manuscrito e o procuram\"}",
                            Name = "Descobriu um Manuscrito",
                            Type = 1,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000009"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataJson = "{\"TriggeringEvent\":\"Foi tra\\u00EDdo por algu\\u00E9m de confian\\u00E7a\",\"Benefit\":\"-1 dificuldade para perceber trai\\u00E7\\u00E3o/mentira de aliados pr\\u00F3ximos\",\"Complication\":\"Penalidade em testes sociais para formar v\\u00EDnculos r\\u00E1pidos\"}",
                            Name = "Traído por um Aliado",
                            Type = 1,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000010"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataJson = "{\"TriggeringEvent\":\"Feito her\\u00F3ico publicamente reconhecido\",\"Benefit\":\"Reputa\\u00E7\\u00E3o positiva e acesso a favores menores na regi\\u00E3o\",\"Complication\":\"A vila cobra ajuda cont\\u00EDnua; recusar custa reputa\\u00E7\\u00E3o\"}",
                            Name = "Salvou uma Vila",
                            Type = 1,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000011"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataJson = "{\"TriggeringEvent\":\"Um familiar desapareceu ou morreu em uma expedi\\u00E7\\u00E3o\",\"Benefit\":\"-1 dificuldade em testes ligados a rastrear aquele tipo de perigo espec\\u00EDfico\",\"Complication\":\"Obsess\\u00E3o que pode lev\\u00E1-lo a riscos desnecess\\u00E1rios\"}",
                            Name = "Perdeu Alguém na Dungeon",
                            Type = 1,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000012"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataJson = "{\"TriggeringEvent\":\"Selou um pequeno acordo com uma entidade\",\"Benefit\":\"Pequeno benef\\u00EDcio sobrenatural (definido com o Mestre)\",\"Complication\":\"A entidade cobrar\\u00E1 algo em troca, em algum momento\"}",
                            Name = "Fez um Pacto Menor",
                            Type = 1,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000013"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataJson = "{\"TriggeringEvent\":\"Quase morreu de uma praga\",\"Benefit\":\"Resist\\u00EAncia aumentada contra doen\\u00E7as e venenos\",\"Complication\":\"Carrega uma sequela f\\u00EDsica leve e permanente\"}",
                            Name = "Sobreviveu a uma Doença Grave",
                            Type = 1,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000014"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataJson = "{\"TriggeringEvent\":\"Teve a reputa\\u00E7\\u00E3o manchada por um crime que n\\u00E3o cometeu\",\"Benefit\":\"B\\u00F4nus em Diplomacia quando precisa se defender de acusa\\u00E7\\u00F5es\",\"Complication\":\"Ainda \\u00E9 malvisto ou procurado em determinado lugar\"}",
                            Name = "Acusado Injustamente",
                            Type = 1,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000015"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataJson = "{\"TriggeringEvent\":\"Sabe de algo perigoso que n\\u00E3o devia saber\",\"Benefit\":\"Possui informa\\u00E7\\u00E3o valiosa, negoci\\u00E1vel\",\"Complication\":\"Outros sabem que ele sabe \\u2014 e isso o torna um alvo\"}",
                            Name = "Guardião de um Segredo",
                            Type = 1,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000016"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataJson = "{\"TriggeringEvent\":\"Passou por um ritual incompleto\",\"Benefit\":\"Sensibilidade leve a presen\\u00E7as m\\u00E1gicas pr\\u00F3ximas\",\"Complication\":\"A marca do ritual \\u00E9 percept\\u00EDvel ou reage mal a certos est\\u00EDmulos\"}",
                            Name = "Marcado por um Ritual",
                            Type = 1,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000017"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataJson = "{\"TriggeringEvent\":\"Deve a vida a algu\\u00E9m que nunca identificou\",\"Benefit\":\"Possui um contato misterioso que pode ajudar 1x\",\"Complication\":\"N\\u00E3o sabe quem foi \\u2014 a d\\u00EDvida pode ser cobrada a qualquer momento\"}",
                            Name = "Resgatado por Estranhos",
                            Type = 1,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000018"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataJson = "{\"TriggeringEvent\":\"Um inc\\u00EAndio ou colapso destruiu sua vida anterior\",\"Benefit\":\"B\\u00F4nus de Vontade contra desespero e perda\",\"Complication\":\"N\\u00E3o possui posses, contatos ou apoio financeiro antigos\"}",
                            Name = "Perdeu Tudo em um Desastre",
                            Type = 1,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000019"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataJson = "{\"TriggeringEvent\":\"Viu de perto o fen\\u00F4meno mais temido do mundo\",\"Benefit\":\"Resist\\u00EAncia a p\\u00E2nico diante de fen\\u00F4menos dimensionais\",\"Complication\":\"Hipervigil\\u00E2ncia: penalidade em ambientes que lembram o evento\"}",
                            Name = "Testemunhou uma Ruptura",
                            Type = 1,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000020"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataJson = "{\"TriggeringEvent\":\"Cresceu dentro da pr\\u00F3pria institui\\u00E7\\u00E3o\",\"Benefit\":\"B\\u00F4nus em testes administrativos/burocr\\u00E1ticos internos da Guilda\",\"Complication\":\"Nunca teve vida \\u0022normal\\u0022: penalidade leve em situa\\u00E7\\u00F5es sociais fora da Guilda\"}",
                            Name = "Criado pela Guilda",
                            Type = 1,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Ruptura.Domain.Entities.CharacterSheet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("GrantedByGameMasterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("CharacterSheets");
                });

            modelBuilder.Entity("Ruptura.Domain.Entities.GuildMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GuildSheetId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GuildSheetId");

                    b.ToTable("GuildMemberships");
                });

            modelBuilder.Entity("Ruptura.Domain.Entities.GuildSheet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByGameMasterId")
                        .HasColumnType("uuid");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GuildName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("GuildSheets");
                });

            modelBuilder.Entity("Ruptura.Domain.Entities.InviteCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByGameMasterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UsedByPlayerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("InviteCodes");
                });

            modelBuilder.Entity("Ruptura.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("RecruitedByGameMasterId")
                        .HasColumnType("uuid");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Ruptura.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Ruptura.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ruptura.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Ruptura.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ruptura.Domain.Entities.GuildMembership", b =>
                {
                    b.HasOne("Ruptura.Domain.Entities.GuildSheet", "GuildSheet")
                        .WithMany("Memberships")
                        .HasForeignKey("GuildSheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuildSheet");
                });

            modelBuilder.Entity("Ruptura.Domain.Entities.GuildSheet", b =>
                {
                    b.Navigation("Memberships");
                });
#pragma warning restore 612, 618
        }
    }
}
